# Generated by Django 4.1.3 on 2022-11-20 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('jugados', models.IntegerField(default=0)),
                ('ganados', models.IntegerField(default=0)),
                ('empatados', models.IntegerField(default=0)),
                ('perdidos', models.IntegerField(default=0)),
                ('goles_a_favor', models.IntegerField(default=0)),
                ('goles_en_contra', models.IntegerField(default=0)),
                ('diferencia_goles', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('liga', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='liga.liga')),
            ],
        ),
    ]
