# Generated by Django 4.1.3 on 2023-02-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0002_alter_equipo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updating_date', models.DateField(auto_now=True, verbose_name='Fecha actualización')),
                ('deleting_date', models.DateField(auto_now=True, verbose_name='Fecha eliminación')),
                ('nombre', models.CharField(max_length=55)),
                ('apellido', models.CharField(max_length=55)),
                ('edad', models.PositiveIntegerField()),
                ('goles', models.PositiveSmallIntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
    ]
