# Generated by Django 4.1.3 on 2023-02-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liga',
            options={'verbose_name': 'Liga', 'verbose_name_plural': 'Ligas'},
        ),
    ]
